### ISSUE TITLE
Release application Familiada-POLSL.exe

### ISSUE THREAD

**Issue by PitaLife** [BialySztorm/Familiada-POLSL#1]
please release the application that you made in .exe format

**Comment by BialySztorm** [comment]
it's WIP for now, will be completed in about a month

**Comment by PitaLife** [comment]
how long have you released this software in .exe format

**Comment by BialySztorm** [comment]
Just released:
[Release zip](https://github.com/BialySztorm/Familiada-POLSL/releases/tag/v1.0.0)

**Comment by PitaLife** [comment]
I've tried it. but apparently there is this info "The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-win-core-synch-I1-2-0.dll

**Comment by BialySztorm** [comment]
> I've tried it. but apparently there is this info "The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-win-core-synch-I1-2-0.dll

You tried deploy it, or the error is from exe?, and did you extracted from zip all files?
You can always download it from itch launcher https://bialysztorm.itch.io/familiada

**Comment by PitaLife** [comment]
when did you make that game but the questions and answers were made by ourselves

**Comment by BialySztorm** [comment]
You can replace the content in data files
